/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as MediaIndexRouteImport } from './routes/media/index'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as StoriesNewRouteImport } from './routes/stories/new'
import { Route as StoriesStoryIdRouteImport } from './routes/stories/$storyId'
import { Route as FinancePortfolioRouteImport } from './routes/finance/portfolio'
import { Route as FinanceCategoriesRouteImport } from './routes/finance/categories'
import { Route as ApiReportErrorRouteImport } from './routes/api.report-error'
import { Route as ApiTestStoriesRouteImport } from './routes/api.test.stories'
import { Route as ApiTestPortfolioRouteImport } from './routes/api.test.portfolio'
import { Route as ApiTestMediaRouteImport } from './routes/api.test.media'
import { Route as ApiTestLoginRouteImport } from './routes/api.test.login'
import { Route as ApiTestFinanceRouteImport } from './routes/api.test.finance'
import { Route as ApiTestCategoriesRouteImport } from './routes/api.test.categories'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api.telegram.webhook'
import { Route as ApiTelegramSetupRouteImport } from './routes/api.telegram.setup'
import { Route as ApiGithubWebhookRouteImport } from './routes/api.github.webhook'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthGoogleRouteImport } from './routes/api.auth.google'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api.auth.callback.google'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesNewRoute = StoriesNewRouteImport.update({
  id: '/stories/new',
  path: '/stories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdRoute = StoriesStoryIdRouteImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePortfolioRoute = FinancePortfolioRouteImport.update({
  id: '/finance/portfolio',
  path: '/finance/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCategoriesRoute = FinanceCategoriesRouteImport.update({
  id: '/finance/categories',
  path: '/finance/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportErrorRoute = ApiReportErrorRouteImport.update({
  id: '/api/report-error',
  path: '/api/report-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestStoriesRoute = ApiTestStoriesRouteImport.update({
  id: '/api/test/stories',
  path: '/api/test/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestPortfolioRoute = ApiTestPortfolioRouteImport.update({
  id: '/api/test/portfolio',
  path: '/api/test/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestMediaRoute = ApiTestMediaRouteImport.update({
  id: '/api/test/media',
  path: '/api/test/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestLoginRoute = ApiTestLoginRouteImport.update({
  id: '/api/test/login',
  path: '/api/test/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestFinanceRoute = ApiTestFinanceRouteImport.update({
  id: '/api/test/finance',
  path: '/api/test/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestCategoriesRoute = ApiTestCategoriesRouteImport.update({
  id: '/api/test/categories',
  path: '/api/test/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramSetupRoute = ApiTelegramSetupRouteImport.update({
  id: '/api/telegram/setup',
  path: '/api/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/report-error': typeof ApiReportErrorRoute
  '/finance/categories': typeof FinanceCategoriesRoute
  '/finance/portfolio': typeof FinancePortfolioRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/new': typeof StoriesNewRoute
  '/finance/': typeof FinanceIndexRoute
  '/media/': typeof MediaIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/telegram/setup': typeof ApiTelegramSetupRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/test/categories': typeof ApiTestCategoriesRoute
  '/api/test/finance': typeof ApiTestFinanceRoute
  '/api/test/login': typeof ApiTestLoginRoute
  '/api/test/media': typeof ApiTestMediaRoute
  '/api/test/portfolio': typeof ApiTestPortfolioRoute
  '/api/test/stories': typeof ApiTestStoriesRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/report-error': typeof ApiReportErrorRoute
  '/finance/categories': typeof FinanceCategoriesRoute
  '/finance/portfolio': typeof FinancePortfolioRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/new': typeof StoriesNewRoute
  '/finance': typeof FinanceIndexRoute
  '/media': typeof MediaIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/telegram/setup': typeof ApiTelegramSetupRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/test/categories': typeof ApiTestCategoriesRoute
  '/api/test/finance': typeof ApiTestFinanceRoute
  '/api/test/login': typeof ApiTestLoginRoute
  '/api/test/media': typeof ApiTestMediaRoute
  '/api/test/portfolio': typeof ApiTestPortfolioRoute
  '/api/test/stories': typeof ApiTestStoriesRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/report-error': typeof ApiReportErrorRoute
  '/finance/categories': typeof FinanceCategoriesRoute
  '/finance/portfolio': typeof FinancePortfolioRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/new': typeof StoriesNewRoute
  '/finance/': typeof FinanceIndexRoute
  '/media/': typeof MediaIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/telegram/setup': typeof ApiTelegramSetupRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/test/categories': typeof ApiTestCategoriesRoute
  '/api/test/finance': typeof ApiTestFinanceRoute
  '/api/test/login': typeof ApiTestLoginRoute
  '/api/test/media': typeof ApiTestMediaRoute
  '/api/test/portfolio': typeof ApiTestPortfolioRoute
  '/api/test/stories': typeof ApiTestStoriesRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/report-error'
    | '/finance/categories'
    | '/finance/portfolio'
    | '/stories/$storyId'
    | '/stories/new'
    | '/finance/'
    | '/media/'
    | '/stories/'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/github/webhook'
    | '/api/telegram/setup'
    | '/api/telegram/webhook'
    | '/api/test/categories'
    | '/api/test/finance'
    | '/api/test/login'
    | '/api/test/media'
    | '/api/test/portfolio'
    | '/api/test/stories'
    | '/api/auth/callback/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/report-error'
    | '/finance/categories'
    | '/finance/portfolio'
    | '/stories/$storyId'
    | '/stories/new'
    | '/finance'
    | '/media'
    | '/stories'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/github/webhook'
    | '/api/telegram/setup'
    | '/api/telegram/webhook'
    | '/api/test/categories'
    | '/api/test/finance'
    | '/api/test/login'
    | '/api/test/media'
    | '/api/test/portfolio'
    | '/api/test/stories'
    | '/api/auth/callback/google'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/report-error'
    | '/finance/categories'
    | '/finance/portfolio'
    | '/stories/$storyId'
    | '/stories/new'
    | '/finance/'
    | '/media/'
    | '/stories/'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/github/webhook'
    | '/api/telegram/setup'
    | '/api/telegram/webhook'
    | '/api/test/categories'
    | '/api/test/finance'
    | '/api/test/login'
    | '/api/test/media'
    | '/api/test/portfolio'
    | '/api/test/stories'
    | '/api/auth/callback/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiReportErrorRoute: typeof ApiReportErrorRoute
  FinanceCategoriesRoute: typeof FinanceCategoriesRoute
  FinancePortfolioRoute: typeof FinancePortfolioRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRoute
  StoriesNewRoute: typeof StoriesNewRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  MediaIndexRoute: typeof MediaIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiTelegramSetupRoute: typeof ApiTelegramSetupRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiTestCategoriesRoute: typeof ApiTestCategoriesRoute
  ApiTestFinanceRoute: typeof ApiTestFinanceRoute
  ApiTestLoginRoute: typeof ApiTestLoginRoute
  ApiTestMediaRoute: typeof ApiTestMediaRoute
  ApiTestPortfolioRoute: typeof ApiTestPortfolioRoute
  ApiTestStoriesRoute: typeof ApiTestStoriesRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/new': {
      id: '/stories/new'
      path: '/stories/new'
      fullPath: '/stories/new'
      preLoaderRoute: typeof StoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/portfolio': {
      id: '/finance/portfolio'
      path: '/finance/portfolio'
      fullPath: '/finance/portfolio'
      preLoaderRoute: typeof FinancePortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/categories': {
      id: '/finance/categories'
      path: '/finance/categories'
      fullPath: '/finance/categories'
      preLoaderRoute: typeof FinanceCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-error': {
      id: '/api/report-error'
      path: '/api/report-error'
      fullPath: '/api/report-error'
      preLoaderRoute: typeof ApiReportErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/stories': {
      id: '/api/test/stories'
      path: '/api/test/stories'
      fullPath: '/api/test/stories'
      preLoaderRoute: typeof ApiTestStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/portfolio': {
      id: '/api/test/portfolio'
      path: '/api/test/portfolio'
      fullPath: '/api/test/portfolio'
      preLoaderRoute: typeof ApiTestPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/media': {
      id: '/api/test/media'
      path: '/api/test/media'
      fullPath: '/api/test/media'
      preLoaderRoute: typeof ApiTestMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/login': {
      id: '/api/test/login'
      path: '/api/test/login'
      fullPath: '/api/test/login'
      preLoaderRoute: typeof ApiTestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/finance': {
      id: '/api/test/finance'
      path: '/api/test/finance'
      fullPath: '/api/test/finance'
      preLoaderRoute: typeof ApiTestFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/categories': {
      id: '/api/test/categories'
      path: '/api/test/categories'
      fullPath: '/api/test/categories'
      preLoaderRoute: typeof ApiTestCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/setup': {
      id: '/api/telegram/setup'
      path: '/api/telegram/setup'
      fullPath: '/api/telegram/setup'
      preLoaderRoute: typeof ApiTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiReportErrorRoute: ApiReportErrorRoute,
  FinanceCategoriesRoute: FinanceCategoriesRoute,
  FinancePortfolioRoute: FinancePortfolioRoute,
  StoriesStoryIdRoute: StoriesStoryIdRoute,
  StoriesNewRoute: StoriesNewRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  MediaIndexRoute: MediaIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiTelegramSetupRoute: ApiTelegramSetupRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiTestCategoriesRoute: ApiTestCategoriesRoute,
  ApiTestFinanceRoute: ApiTestFinanceRoute,
  ApiTestLoginRoute: ApiTestLoginRoute,
  ApiTestMediaRoute: ApiTestMediaRoute,
  ApiTestPortfolioRoute: ApiTestPortfolioRoute,
  ApiTestStoriesRoute: ApiTestStoriesRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
